# Generated by Django 5.2.7 on 2025-10-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('disciplina', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True, null=True)),
                ('is_voluntario', models.BooleanField(default=False, help_text='Marque se o professor oferece aulas de forma gratuita/voluntária.')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
            },
        ),
    ]
